gazebo_ros_control:
  pid_gains:
    F1M1:
      p: 100.0
      i: 0.01
      d: 1.0
    F1M2:
      p: 100.0
      i: 0.01
      d: 1.0
    F1M3:
      p: 100.0
      i: 0.01
      d: 1.0
    F1M4:
      p: 100.0
      i: 0.01
      d: 1.0
    F2M1:
      p: 100.0
      i: 0.01
      d: 1.0
    F2M2:
      p: 100.0
      i: 0.01
      d: 1.0
    F2M3:
      p: 100.0
      i: 0.01
      d: 1.0
    F2M4:
      p: 100.0
      i: 0.01
      d: 1.0
    F3M1:
      p: 100.0
      i: 0.01
      d: 1.0
    F3M2:
      p: 100.0
      i: 0.01
      d: 1.0
    F3M3:
      p: 100.0
      i: 0.01
      d: 1.0
    F3M4:
      p: 100.0
      i: 0.01
      d: 1.0
      
