delto:
  Distance_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - Distance
    constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      Distance: {trajectory: 0.1, goal: 0.1}
    stop_trajectory_duration: 0.5
    state_publish_rate:  50
    action_monitor_rate: 10

